import type { BuildSeed } from "./seed-types";
import {
  CombatStyle,
  Difficulty,
  ModeFocus,
  OperatingSystemType,
  ProgressionStage,
} from "./constants";

export const cyberpunkBuildSeeds = [
  {
    slug: "ghostwire-netrunner",
    name: "Ghostwire Netrunner",
    primaryArchetype: "Netrunner",
    summary:
      "A high-Intelligence cyberdeck route built around Overclock, queued control hacks, and smart-weapon cleanup.",
    description:
      "Ghostwire Netrunner follows the strongest community netrunner pattern: push Intelligence and Technical Ability to the ceiling, keep survivability tools ready for Overclock, and use utility hacks to multiply your real damage instead of blindly spamming every quickhack slot.",
    playstyle:
      "Stealth-first netrunning with queued quickhacks, Overclock health conversions, camera routing, and smart-weapon cleanup when somebody survives the opening volley.",
    difficulty: Difficulty.ADVANCED,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.HACKING,
    stealthRating: 9,
    loudRating: 2,
    hackingRating: 10,
    mobilityRating: 5,
    survivabilityRating: 4,
    burstRating: 8,
    utilityRating: 10,
    pveRating: 10,
    pvpRating: 0,
    progressionCurve: "Comfortable early through cameras and Ping, truly oppressive once Overclock and top cyberdecks arrive, and nearly unfair once RAM support and healing chrome let you chain fights together.",
    difficultyNotes:
      "Massively powerful, but it falls apart if you lose sightline discipline or trigger Overclock without healing support ready.",
    isFeatured: true,
    sortOrder: 1,
    attributeStats: [
      { key: "body", label: "Body", value: 15 },
      { key: "reflexes", label: "Reflexes", value: 9 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 20 },
      { key: "cool", label: "Cool", value: 17 },
    ],
    supportStats: [
      { key: "ram", label: "RAM economy", value: 98 },
      { key: "stealth", label: "Stealth control", value: 92 },
      { key: "spread", label: "Hack spread", value: 95 },
      { key: "recovery", label: "Recovery", value: 74 },
    ],
    weapons: [
      {
        name: "Yinglong",
        slot: "Primary",
        scalingOrProfile: "Smart SMG",
        description: "The best direct-combat fallback once your quickhacks have already destabilized the room.",
      },
      {
        name: "Genjiroh",
        slot: "Secondary",
        scalingOrProfile: "Smart pistol",
        description: "A great companion for cleaner stealth entries or precise cleanup after hack chains land.",
      },
      {
        name: "Monowire",
        slot: "Arms",
        scalingOrProfile: "Intelligence synergy",
        description: "Keeps the build dangerous when enemies finally collapse the distance.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Queue Master", tree: "Intelligence", description: "Lets multiple quickhacks collapse into one decisive system crash." },
      { name: "Overclock", tree: "Intelligence", description: "Converts health into RAM throughput for brutal endgame bursts." },
      { name: "Embedded Vulnerability", tree: "Intelligence", description: "Rewards precise target prep with extra damage." },
      { name: "License to Chrome", tree: "Technical Ability", description: "Expands the cyberware budget so the cyberdeck build stays elite." },
    ],
    cyberware: [
      { name: "Ex-Disk", slot: "Frontal Cortex", description: "Extra RAM that makes your opening volley much safer." },
      { name: "RAM Manager", slot: "Frontal Cortex", description: "Emergency RAM support for longer fights." },
      { name: "Biomonitor", slot: "Circulatory System", description: "A safety net that matters much more once Overclock starts spending your health." },
      { name: "Blood Pump", slot: "Circulatory System", description: "The cleanest answer to long Overclock chains and sudden pressure." },
    ],
    operatingSystems: [
      {
        name: "Tetratronic Rippler",
        type: OperatingSystemType.CYBERDECK,
        description: "The top-end cyberdeck for chaining quickhacks, stacking queue value, and deleting elite targets quickly.",
      },
      {
        name: "NetWatch Netdriver",
        type: OperatingSystemType.CYBERDECK,
        description: "A strong alternative when you want more comfortable camera routing and utility-oriented map control.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Solve fights through sightlines and cameras",
        description: "Early hacking already feels powerful when you play through cameras, Ping, and cover instead of frontal firefights.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Build the Overclock safety net",
        description: "Once cyberware, RAM support, and key Intelligence perks arrive, you can spend health aggressively without instantly collapsing in return.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Chain utility hacks into lethal ones",
        description: "Endgame play is about sequencing non-lethal setup hacks before the killing hack so every queue feels deliberate and explosive.",
      },
    ],
    strengths: [
      "One of the strongest PvE control builds in the game.",
      "Can solve encounters before direct combat even begins.",
      "Overclock gives it elite endgame tempo once health sustain is in place.",
      "Flexible fallback options through smart weapons and monowire.",
      "Especially satisfying for tactical players who enjoy planning and sequencing.",
    ],
    weaknesses: [
      "Low survivability if stealth breaks badly.",
      "The full fantasy only opens up after cyberware and perk thresholds.",
      "Less appealing if you want constant gunfire.",
      "Overclock punishes sloppy health management very quickly.",
      "For some players, it can feel so strong that it removes tension.",
    ],
    tags: [
      { slug: "hacker", weight: 5 },
      { slug: "stealth", weight: 5 },
      { slug: "quickhacks", weight: 5 },
      { slug: "crowd-control", weight: 5 },
      { slug: "precision", weight: 4 },
      { slug: "glass-cannon", weight: 4 },
      { slug: "pve", weight: 5 },
    ],
    alternatives: [
      { slug: "synapse-smartgunner", reason: "Keeps the Intelligence identity while adding a more direct firing style and more mobility." },
      { slug: "quantum-longshot", reason: "Better if you want hacker support around measured long-range kills." },
    ],
  },
  {
    slug: "apogee-ronin",
    name: "Apogee Ronin",
    primaryArchetype: "Sandevistan Katana",
    summary:
      "A time-dilation katana build built around Byakko or Scalpel, dash chains, and Apogee kill extensions.",
    description:
      "Apogee Ronin follows the classic community Sandevistan-katana route: raise Reflexes and Technical Ability first, then turn Militech Apogee into a room-clearing engine with Byakko, Scalpel, and just enough defensive chrome to survive greedy entries.",
    playstyle:
      "Hyper-mobile melee with dash entries, Sandevistan kill chains, and blade pressure that snowballs off every clean reset.",
    difficulty: Difficulty.INTERMEDIATE,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.MELEE,
    stealthRating: 5,
    loudRating: 9,
    hackingRating: 1,
    mobilityRating: 10,
    survivabilityRating: 6,
    burstRating: 10,
    utilityRating: 6,
    pveRating: 9,
    pvpRating: 0,
    progressionCurve: "Feels stylish immediately, spikes hard with real dash tech, and becomes absurd once Apogee starts extending kills into full-room clears.",
    difficultyNotes:
      "Mistakes are expensive between cooldown gaps, and the build is only truly safe when you learn exactly how much distance a single Sandevistan window buys you.",
    isFeatured: true,
    sortOrder: 2,
    attributeStats: [
      { key: "body", label: "Body", value: 15 },
      { key: "reflexes", label: "Reflexes", value: 20 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 3 },
      { key: "cool", label: "Cool", value: 20 },
    ],
    supportStats: [
      { key: "mobility", label: "Mobility", value: 100 },
      { key: "crit", label: "Crit flow", value: 88 },
      { key: "mitigation", label: "Damage mitigation", value: 72 },
      { key: "uptime", label: "Sandevistan uptime", value: 90 },
    ],
    weapons: [
      {
        name: "Byakko",
        slot: "Primary",
        scalingOrProfile: "Katana",
        description: "Turns every opening into a chain of leaps and high-speed blade pressure.",
      },
      {
        name: "Scalpel",
        slot: "Secondary",
        scalingOrProfile: "Katana",
        description: "A cleaner precision option when you want more controlled Sandevistan punishment than pure Byakko snowballing.",
      },
      {
        name: "Satori",
        slot: "Crit swap",
        scalingOrProfile: "Katana",
        description: "A high-crit alternative for players who want a more surgical version of the time-slow katana loop.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Dash", tree: "Reflexes", description: "Baseline mobility that makes the build feel alive." },
      { name: "Blender", tree: "Reflexes", description: "An aggressive blade perk for pressure on wounded enemies." },
      { name: "Shinobi", tree: "Cool", description: "Supports stealth entries and openings through mobile angles." },
      { name: "Edgerunner", tree: "Technical Ability", description: "Expands the cyberware budget so the body can keep up with the aggression." },
    ],
    cyberware: [
      { name: "Kerenzikov", slot: "Nervous System", description: "Extra slow-time and survivability when your dash line gets messy." },
      { name: "Micro Rotors", slot: "Nervous System", description: "Preserves the insane tempo of blade strikes." },
      { name: "Dense Marrow", slot: "Skeleton", description: "Adds direct close-range pressure and stronger finishers." },
      { name: "Chitin", slot: "Subdermal Armor", description: "Makes the build much less fragile during the moments between one kill chain and the next." },
    ],
    operatingSystems: [
      {
        name: "Militech Apogee Sandevistan",
        type: OperatingSystemType.SANDEVISTAN,
        description: "The defining OS for elite melee tempo and kill chains.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Learn the dash-before-damage loop",
        description: "Even before the best OS arrives, good dash habits and blade fundamentals already make the build strong.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Stretch every Sandevistan activation",
        description: "Midgame is about learning exactly how much room, stamina, and kill pressure a single slow-time activation gives you.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Convert the build into a room-clear engine",
        description: "When Apogee, cyberware, and crit flow align, most encounters become speedrun exercises.",
      },
    ],
    strengths: [
      "Unmatched mobility and stylish lethality.",
      "Very high burst damage while the OS is active.",
      "Feels incredible once movement clicks.",
      "Can switch between stealth entry and loud cleanup.",
    ],
    weaknesses: [
      "Error windows are punishing outside slow time.",
      "Weaker against players who dislike close-range risk.",
      "Always demands attention in aggressive fights.",
      "Can feel too specialized if you want hacking support.",
    ],
    tags: [
      { slug: "melee", weight: 5 },
      { slug: "blades", weight: 5 },
      { slug: "mobility", weight: 5 },
      { slug: "explosive", weight: 5 },
      { slug: "precision", weight: 3 },
      { slug: "execution-heavy", weight: 4 },
      { slug: "pve", weight: 4 },
    ],
    alternatives: [
      { slug: "midnight-suppressor", reason: "Choose this if you want stealth precision with less emphasis on melee." },
      { slug: "chrome-juggernaut", reason: "For players who want loud close-range dominance with more survivability and less mechanical demand." },
    ],
  },
  {
    slug: "midnight-suppressor",
    name: "Midnight Suppressor",
    primaryArchetype: "Stealth Pistol",
    summary:
      "A stealth-shooter route built around Her Majesty, optical camo, and one-shot head chains under Sandevistan.",
    description:
      "Midnight Suppressor takes the community stealth route seriously: max Cool and Technical Ability, open with suppressed headshots, use Sandevistan only to extend clean kill chains, and keep a harder-hitting backup weapon ready when stealth breaks.",
    playstyle:
      "Patient infiltration with headshots, optical-camo resets, Sandevistan lining, and clean recoveries before alarms spiral.",
    difficulty: Difficulty.INTERMEDIATE,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.RANGED,
    stealthRating: 10,
    loudRating: 2,
    hackingRating: 2,
    mobilityRating: 8,
    survivabilityRating: 5,
    burstRating: 8,
    utilityRating: 7,
    pveRating: 9,
    pvpRating: 0,
    progressionCurve: "Stable from the start, then snowballs once Cool perks, optics, and better suppressed pistols make each headshot chain easier to sustain.",
    difficultyNotes:
      "More forgiving than netrunning, but it still demands route planning and real aim; misses are what cause the build to unravel.",
    isFeatured: false,
    sortOrder: 3,
    attributeStats: [
      { key: "body", label: "Body", value: 15 },
      { key: "reflexes", label: "Reflexes", value: 15 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 3 },
      { key: "cool", label: "Cool", value: 20 },
    ],
    supportStats: [
      { key: "headshot", label: "Headshot accuracy", value: 94 },
      { key: "stealth", label: "Stealth flow", value: 97 },
      { key: "reload", label: "Reload tempo", value: 80 },
      { key: "recovery", label: "Reset tools", value: 82 },
    ],
    weapons: [
      {
        name: "Her Majesty",
        slot: "Primary",
        scalingOrProfile: "Heavy pistol",
        description: "The ideal suppressed weapon for clean optical kills.",
      },
      {
        name: "Death and Taxes",
        slot: "Secondary",
        scalingOrProfile: "Pistol",
        description: "A superb backup when you want a faster, more forgiving stealth pistol that still rewards double-headshot discipline.",
      },
      {
        name: "Overwatch",
        slot: "Long-range swap",
        scalingOrProfile: "Suppressed sniper rifle",
        description: "Lets you start clearing a compound from extreme range before the pistol chain even begins.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Tungsten Steel Nerves", tree: "Cool", description: "Massive precision rewards for the whole headshot scheme." },
      { name: "Focus", tree: "Cool", description: "Supports measured long-range peeks and steady aim." },
      { name: "Deadeye", tree: "Cool", description: "Turns patient pistol play into devastating crit chains." },
      { name: "License to Chrome", tree: "Technical Ability", description: "Keeps the budget for stealth cyberware competitive." },
    ],
    cyberware: [
      { name: "Optical Camo", slot: "Subdermal Armor", description: "Lets you correct route mistakes or extend a silent clear." },
      { name: "Kiroshi Oracle Optics", slot: "Eyes", description: "Elite visibility and target clarity for clean peeks." },
      { name: "Long-Range Visual Interface", slot: "Frontal Cortex", description: "Improves ranged accuracy and detection control." },
      { name: "Synaptic Accelerator", slot: "Nervous System", description: "Gives you room to maneuver if you are unexpectedly spotted." },
    ],
    operatingSystems: [
      {
        name: "Militech Falcon Sandevistan",
        type: OperatingSystemType.SANDEVISTAN,
        description: "Used not for close-range assault, but to line up perfect stealth shots under pressure.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Build the headshot route first",
        description: "Early success comes from route discipline, suppressed weapons, and smart use of cover rather than raw stats.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Layer optics and Sandevistan around clean peeks",
        description: "Midgame pistol perks and optics make every clean peek strong enough to break groups before alarms spread.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Turn stealth into a self-sustaining chain",
        description: "Late-game Cool levels, optical camo, and better pistols make the build feel like a true compound-clear specialist instead of a cautious solo infiltrator.",
      },
    ],
    strengths: [
      "Elite stealth and precision feel.",
      "Excellent feedback for careful shooting.",
      "Smooth progression without relying on a single gimmick.",
      "A great build for mission routing and infiltration.",
    ],
    weaknesses: [
      "Less burst potential if the fight drags into loud territory.",
      "Headshot misses are costly.",
      "Crowd control is weaker than quickhacks or shotguns.",
      "Requires patience that some players may read as slow.",
    ],
    tags: [
      { slug: "ranged", weight: 5 },
      { slug: "stealth", weight: 5 },
      { slug: "precision", weight: 5 },
      { slug: "methodical", weight: 5 },
      { slug: "mobility", weight: 3 },
      { slug: "pve", weight: 4 },
      { slug: "execution-heavy", weight: 3 },
    ],
    alternatives: [
      { slug: "quantum-longshot", reason: "Choose this for measured long-range peeks with more tech punch and less reliance on stealth." },
      { slug: "ghostwire-netrunner", reason: "For a quieter infiltration route that solves groups through systems instead of headshots." },
    ],
  },
  {
    slug: "chrome-juggernaut",
    name: "Chrome Juggernaut",
    primaryArchetype: "Shotgun Tank",
    summary:
      "A Berserk breacher that mixes shotgun pressure, Gorilla Arms, and Body-first survivability into an easy loud-combat monster.",
    description:
      "Chrome Juggernaut leans closer to the community Berserk and Hunter routes: Body and Technical Ability carry the defense, Berserk windows let you breach safely, and shotguns or blunt finishers erase anything still standing in your face.",
    playstyle:
      "Door-kicking loud combat with Berserk activations, shotgun body shots, Gorilla Arms cleanup, and healing timed around reckless pushes.",
    difficulty: Difficulty.BEGINNER,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.MELEE,
    stealthRating: 1,
    loudRating: 10,
    hackingRating: 0,
    mobilityRating: 5,
    survivabilityRating: 10,
    burstRating: 9,
    utilityRating: 5,
    pveRating: 9,
    pvpRating: 0,
    progressionCurve: "Strong from the start, then keeps getting meaner as Body perks, healing chrome, and Berserk uptime all start overlapping.",
    difficultyNotes:
      "Extremely approachable, but it still rewards players who alternate healing, mitigation, and Berserk instead of face-tanking at random.",
    isFeatured: true,
    sortOrder: 4,
    attributeStats: [
      { key: "body", label: "Body", value: 20 },
      { key: "reflexes", label: "Reflexes", value: 15 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 3 },
      { key: "cool", label: "Cool", value: 15 },
    ],
    supportStats: [
      { key: "armor", label: "Armor", value: 95 },
      { key: "mitigation", label: "Damage mitigation", value: 92 },
      { key: "healing", label: "Combat sustain", value: 90 },
      { key: "stagger", label: "Stagger power", value: 88 },
    ],
    weapons: [
      {
        name: "Guts",
        slot: "Primary",
        scalingOrProfile: "Heavy shotgun",
        description: "Insane close-range damage and a perfect thematic fit for assault play.",
      },
      {
        name: "Order",
        slot: "Secondary",
        scalingOrProfile: "Tech shotgun",
        description: "Adds charged tech damage when a tougher target refuses to go down immediately.",
      },
      {
        name: "Gorilla Arms",
        slot: "Arms",
        scalingOrProfile: "Body-scaled melee",
        description: "Backup brutality for enemies that survive the first volley.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Painkiller", tree: "Body", description: "Keeps you alive during messy breaching plays." },
      { name: "Adrenaline Rush", tree: "Body", description: "Turns aggression into survivability in the most direct way possible." },
      { name: "Doom Launcher", tree: "Technical Ability", description: "Expands the value of loud combat and cyberware investment." },
      { name: "Edgerunner", tree: "Technical Ability", description: "Lets you go all-in on heavy chrome without compromise." },
    ],
    cyberware: [
      { name: "Axolotl", slot: "Frontal Cortex", description: "The cleanest way to keep loud-cyberware uptime rolling after each breach." },
      { name: "Blood Pump", slot: "Circulatory System", description: "Reliable emergency sustain under heavy fire." },
      { name: "Chitin", slot: "Subdermal Armor", description: "Flat durability that smooths out loud-content spikes." },
      { name: "Dense Marrow", slot: "Skeleton", description: "More damage for both the shotgun and fist finishers." },
    ],
    operatingSystems: [
      {
        name: "Militech Berserk",
        type: OperatingSystemType.BERSERK,
        description: "Turns the build into an unstoppable assault tool during key windows.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Let Body carry the first half of the game",
        description: "Early Body points instantly make the game easier, and shotguns stay strong with almost no setup.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Turn the build into a real breacher",
        description: "Midgame cyberware turns the build from a brute into a true walking breaching charge.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Keep Berserk windows rolling",
        description: "Late-game sustain and Berserk windows let you pressure elite enemies head-on without complex routing.",
      },
    ],
    strengths: [
      "Very easy to understand and hard to kill.",
      "Outstanding comfort in loud combat.",
      "Shotguns and Berserk make every push feel satisfying.",
      "A great pick for players who dislike fragile builds.",
    ],
    weaknesses: [
      "Minimal flexibility in stealth and hacking.",
      "Can feel blunt if you want subtle systems play.",
      "Effective range is lower than most gun builds.",
      "Some boss-like enemies still demand movement discipline.",
    ],
    tags: [
      { slug: "melee", weight: 3 },
      { slug: "shotguns", weight: 5 },
      { slug: "tank", weight: 5 },
      { slug: "sustain", weight: 5 },
      { slug: "explosive", weight: 4 },
      { slug: "beginner-friendly", weight: 5 },
      { slug: "pve", weight: 5 },
    ],
    alternatives: [
      { slug: "apogee-ronin", reason: "Choose this if you want close-range dominance with much more mobility and execution demand." },
      { slug: "synapse-smartgunner", reason: "For a more ranged, cyberware-heavy build that still feels aggressive." },
    ],
  },
  {
    slug: "synapse-smartgunner",
    name: "Synapse Smartgunner",
    primaryArchetype: "Smart Weapon Hybrid",
    summary:
      "A Reflexes and Intelligence hybrid that turns auto-aim, light support hacks, and aerial positioning into pure combat flow.",
    description:
      "Synapse Smartgunner is for players who want Cyberpunk's tech fantasy without going all-in on a pure hacking build. Smart weapons provide reliable targeting, while light quickhack support and mobile cyberware keep the build fast, responsive, and very modern.",
    playstyle:
      "Aggressive mid-range play with smart targeting, fast support hacks, and sharp movement resets.",
    difficulty: Difficulty.INTERMEDIATE,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.HYBRID,
    stealthRating: 4,
    loudRating: 7,
    hackingRating: 6,
    mobilityRating: 8,
    survivabilityRating: 6,
    burstRating: 8,
    utilityRating: 8,
    pveRating: 9,
    pvpRating: 0,
    progressionCurve: "Improves noticeably with every cyberware tier and smart-link investment.",
    difficultyNotes:
      "A forgiving hybrid that still rewards active movement and target prioritization.",
    isFeatured: false,
    sortOrder: 5,
    attributeStats: [
      { key: "body", label: "Body", value: 12 },
      { key: "reflexes", label: "Reflexes", value: 20 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 15 },
      { key: "cool", label: "Cool", value: 9 },
    ],
    supportStats: [
      { key: "tracking", label: "Target tracking", value: 96 },
      { key: "mobility", label: "Mobility", value: 84 },
      { key: "support", label: "Support hacks", value: 72 },
      { key: "versatility", label: "Versatility", value: 88 },
    ],
    weapons: [
      {
        name: "Yinglong",
        slot: "Primary",
        scalingOrProfile: "Smart SMG",
        description: "A fast, forgiving, tempo-friendly smart-targeting weapon.",
      },
      {
        name: "Divided We Stand",
        slot: "Secondary",
        scalingOrProfile: "Smart assault rifle",
        description: "Excellent for target-dense fights where tracking and status layering matter.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Air Dash", tree: "Reflexes", description: "Makes the build fast and difficult to pin down." },
      { name: "Smart Synergy", tree: "Intelligence", description: "Pushes smart-weapon targeting to elite levels." },
      { name: "License to Chrome", tree: "Technical Ability", description: "The cyberware budget backbone for this build." },
      { name: "Borrowed Time", tree: "Reflexes", description: "Adds survivability while aggressively repositioning." },
    ],
    cyberware: [
      { name: "Smart Link", slot: "Arms", description: "Mandatory equipment that makes the weapon kit sing." },
      { name: "Kerenzikov", slot: "Nervous System", description: "Protects you when you make bold movement decisions." },
      { name: "Newton Module", slot: "Frontal Cortex", description: "Smooths out reset timing and system efficiency." },
      { name: "Heal-on-Kill", slot: "Circulatory System", description: "Keeps long firefights from devolving into chaos." },
    ],
    operatingSystems: [
      {
        name: "NetWatch Netdriver",
        type: OperatingSystemType.CYBERDECK,
        description: "A support cyberdeck that boosts utility without turning the build into a full netrunner.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Play straight, but mobile",
        description: "Early smart weapons are forgiving enough to make movement and encounter tempo your main learning loop.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Hybridize through light hacks",
        description: "Support quickhacks begin to reinforce your fire flow without blurring the build's direct-combat identity.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Turn every room into target-tracking practice",
        description: "Late-game cyberware and mobility perks make multi-target fights almost frictionless.",
      },
    ],
    strengths: [
      "Very smooth, modern-feeling gunplay.",
      "A strong mix of direct combat and cyber utility.",
      "Forgiving targeting helps preserve momentum.",
      "A strong recommendation target for players who want variety without complexity overload.",
    ],
    weaknesses: [
      "Less distinct identity than a pure netrunner or pure blade build.",
      "Can feel gear-dependent before smart-link support gets strong.",
      "Only average stealth options.",
      "Not the highest single-target burst on the roster.",
    ],
    tags: [
      { slug: "hybrid", weight: 5 },
      { slug: "smart-weapons", weight: 5 },
      { slug: "mobility", weight: 4 },
      { slug: "quickhacks", weight: 3 },
      { slug: "reactive", weight: 4 },
      { slug: "pve", weight: 4 },
      { slug: "beginner-friendly", weight: 3 },
    ],
    alternatives: [
      { slug: "ghostwire-netrunner", reason: "Choose this if you want to lean harder into cyberdeck dominance and stealth control." },
      { slug: "chrome-juggernaut", reason: "Better if you want more survivability and a louder direct confrontation." },
    ],
  },
  {
    slug: "quantum-longshot",
    name: "Quantum Longshot",
    primaryArchetype: "Tech Sniper",
    summary:
      "A tech-sniper route built around charged peeks, wall-penetrating shots, and slow-time windows for perfect head placement.",
    description:
      "Quantum Longshot follows the community sniper route: charge the shot from safety, trigger slow time, expose only for the release, and let tech rifles or Rasetsu-style snipers punish through cover before the room can answer.",
    playstyle:
      "Measured long-range play with charge timing, wall penetration, scouting optics, and Sandevistan-assisted headshots.",
    difficulty: Difficulty.ADVANCED,
    primaryMode: ModeFocus.PVE,
    combatStyle: CombatStyle.RANGED,
    stealthRating: 6,
    loudRating: 4,
    hackingRating: 2,
    mobilityRating: 7,
    survivabilityRating: 5,
    burstRating: 9,
    utilityRating: 7,
    pveRating: 8,
    pvpRating: 0,
    progressionCurve: "Can feel merely solid at first, then becomes ferocious once charge timing, optics, and Sandevistan windows all line up correctly.",
    difficultyNotes:
      "A high-reward build that expects accuracy, patience, and honest target selection. The damage is there, but rushed peeks waste the whole idea.",
    isFeatured: false,
    sortOrder: 6,
    attributeStats: [
      { key: "body", label: "Body", value: 15 },
      { key: "reflexes", label: "Reflexes", value: 13 },
      { key: "technical-ability", label: "Technical Ability", value: 20 },
      { key: "intelligence", label: "Intelligence", value: 3 },
      { key: "cool", label: "Cool", value: 20 },
    ],
    supportStats: [
      { key: "penetration", label: "Cover penetration", value: 96 },
      { key: "headshot", label: "Headshot reliability", value: 90 },
      { key: "spotting", label: "Detection tools", value: 84 },
      { key: "control", label: "Encounter control", value: 78 },
    ],
    weapons: [
      {
        name: "Rasetsu",
        slot: "Primary",
        scalingOrProfile: "Tech sniper rifle",
        description: "The ideal endgame sniper for charged, slow-time peeks that instantly erase high-value targets.",
      },
      {
        name: "Breakthrough",
        slot: "Secondary",
        scalingOrProfile: "Tech sniper rifle",
        description: "A superb through-cover rifle that keeps the build lethal before Rasetsu arrives or when you want a more stable fallback.",
      },
    ],
    armorPieces: [],
    talismans: [],
    spells: [],
    perks: [
      { name: "Deadeye", tree: "Cool", description: "Essential for precise scope-based play." },
      { name: "Focus", tree: "Cool", description: "Turns shot lining into stable routine instead of gambling." },
      { name: "Momentum", tree: "Technical Ability", description: "Critical for maximizing tech-weapon windows." },
      { name: "Data Tunneling", tree: "Intelligence", description: "Adds auxiliary cyber utility without blurring the sniper identity." },
    ],
    cyberware: [
      { name: "Kiroshi Oracle Optics", slot: "Eyes", description: "Premium optics for range, clarity, and weak-point tracking." },
      { name: "Long-Range Visual Interface", slot: "Frontal Cortex", description: "Improves shot information and confidence at long range." },
      { name: "Optical Camo", slot: "Subdermal Armor", description: "Lets you reset between peeks when the route gets messy." },
      { name: "Microgenerator", slot: "Circulatory System", description: "Adds a safety burst of damage if enemies suddenly get too close." },
    ],
    operatingSystems: [
      {
        name: "Militech Apogee Sandevistan",
        type: OperatingSystemType.SANDEVISTAN,
        description: "Lets you charge in cover, peek in slow time, and release the shot exactly at the breakpoint you want.",
      },
    ],
    progression: [
      {
        stage: ProgressionStage.EARLY,
        title: "Respect target priority over speed",
        description: "Early sniper success is built on route choice and target priority more than raw stat scaling.",
      },
      {
        stage: ProgressionStage.MID,
        title: "Learn the charge-and-peek rhythm",
        description: "Midgame is where charge timing, optics, and controlled slow-time peeks turn the build from a rifleman into a real sniper.",
      },
      {
        stage: ProgressionStage.LATE,
        title: "Own sightlines before enemies own you",
        description: "Late-game chrome and sniper rifles let you dismantle elite enemies before they ever build pressure on your position.",
      },
    ],
    strengths: [
      "Fantastic long-range burst damage and target deletion.",
      "Very rewarding for accurate players.",
      "Tech-weapon cover penetration creates unique encounter solutions.",
      "Sandevistan turns dangerous peeks into controlled executions.",
      "Excellent at removing elite threats before they can pressure the arena.",
    ],
    weaknesses: [
      "Less forgiving when enemies close distance quickly.",
      "Requires strong aim and patience.",
      "Can feel slower than a dash-pressure build.",
      "Bad peeks are punished harder here than on almost any other ranged setup.",
      "Baseline survivability is lower than tankier loud-combat builds.",
    ],
    tags: [
      { slug: "ranged", weight: 5 },
      { slug: "tech-weapons", weight: 5 },
      { slug: "precision", weight: 5 },
      { slug: "methodical", weight: 5 },
      { slug: "stealth", weight: 3 },
      { slug: "pve", weight: 4 },
      { slug: "execution-heavy", weight: 4 },
    ],
    alternatives: [
      { slug: "midnight-suppressor", reason: "Choose this if you want stealth precision with a faster pistol tempo and less emphasis on long range." },
      { slug: "ghostwire-netrunner", reason: "For players who want to control the map through systems rather than a sightline." },
    ],
  },
] satisfies BuildSeed[];
