import type { TagSeed } from "./seed-types";
import { TagCategory } from "./constants";

export const tagSeeds = [
  { slug: "colossal", label: "Colossal", category: TagCategory.STYLE },
  { slug: "mage", label: "Mage", category: TagCategory.STYLE },
  { slug: "dragon", label: "Dragon Communion", category: TagCategory.STYLE },
  { slug: "faith", label: "Faith", category: TagCategory.STYLE },
  { slug: "spellblade", label: "Spellblade", category: TagCategory.STYLE },
  { slug: "melee", label: "Melee", category: TagCategory.STYLE },
  { slug: "ranged", label: "Ranged", category: TagCategory.STYLE },
  { slug: "spellcaster", label: "Spellcaster", category: TagCategory.STYLE },
  { slug: "hacker", label: "Hacker", category: TagCategory.STYLE },
  { slug: "stealth", label: "Stealth", category: TagCategory.STYLE },
  { slug: "hybrid", label: "Hybrid", category: TagCategory.STYLE },
  { slug: "alchemy", label: "Alchemy", category: TagCategory.STYLE },
  { slug: "signs", label: "Signs", category: TagCategory.STYLE },
  { slug: "mutation", label: "Mutation", category: TagCategory.STYLE },
  { slug: "swordmaster", label: "Swordmaster", category: TagCategory.STYLE },
  { slug: "pyromancy", label: "Pyromancy", category: TagCategory.STYLE },
  { slug: "miracles", label: "Miracles", category: TagCategory.STYLE },
  { slug: "hexes", label: "Hexes", category: TagCategory.STYLE },
  { slug: "motivity", label: "Motivity", category: TagCategory.STYLE },
  { slug: "technique", label: "Technique", category: TagCategory.STYLE },
  { slug: "advance", label: "Advance", category: TagCategory.STYLE },
  { slug: "legion-arm", label: "Legion Arm", category: TagCategory.STYLE },
  { slug: "strength", label: "Strength", category: TagCategory.DAMAGE },
  { slug: "dexterity", label: "Dexterity", category: TagCategory.DAMAGE },
  { slug: "intelligence", label: "Intelligence", category: TagCategory.DAMAGE },
  { slug: "bleed", label: "Bleed", category: TagCategory.DAMAGE },
  { slug: "fire", label: "Fire", category: TagCategory.DAMAGE },
  { slug: "magic", label: "Magic", category: TagCategory.DAMAGE },
  { slug: "frost", label: "Frost", category: TagCategory.DAMAGE },
  { slug: "arcane", label: "Arcane", category: TagCategory.DAMAGE },
  { slug: "blades", label: "Blades", category: TagCategory.DAMAGE },
  { slug: "shotguns", label: "Shotguns", category: TagCategory.DAMAGE },
  { slug: "smart-weapons", label: "Smart Weapons", category: TagCategory.DAMAGE },
  { slug: "tech-weapons", label: "Tech Weapons", category: TagCategory.DAMAGE },
  { slug: "quickhacks", label: "Quickhacks", category: TagCategory.DAMAGE },
  { slug: "adrenaline", label: "Adrenaline", category: TagCategory.DAMAGE },
  { slug: "whirl", label: "Whirl", category: TagCategory.DAMAGE },
  { slug: "bombs", label: "Bombs", category: TagCategory.DAMAGE },
  { slug: "lightning", label: "Lightning", category: TagCategory.DAMAGE },
  { slug: "dark", label: "Dark Damage", category: TagCategory.DAMAGE },
  { slug: "quality", label: "Quality", category: TagCategory.DAMAGE },
  { slug: "ultra-greatsword", label: "Ultra Greatsword", category: TagCategory.DAMAGE },
  { slug: "twinblades", label: "Twinblades", category: TagCategory.DAMAGE },
  { slug: "rapier", label: "Rapier", category: TagCategory.DAMAGE },
  { slug: "poison", label: "Poison", category: TagCategory.DAMAGE },
  { slug: "elemental", label: "Elemental", category: TagCategory.DAMAGE },
  { slug: "fable-arts", label: "Fable Arts", category: TagCategory.DAMAGE },
  { slug: "tank", label: "Tank", category: TagCategory.DEFENSE },
  { slug: "sustain", label: "Sustain", category: TagCategory.DEFENSE },
  { slug: "mobility", label: "Mobility", category: TagCategory.DEFENSE },
  { slug: "perfect-guard", label: "Perfect Guard", category: TagCategory.DEFENSE },
  { slug: "control", label: "Control", category: TagCategory.UTILITY },
  { slug: "utility", label: "Utility", category: TagCategory.UTILITY },
  { slug: "crowd-control", label: "Crowd Control", category: TagCategory.UTILITY },
  { slug: "boss-burst", label: "Boss Burst", category: TagCategory.UTILITY },
  { slug: "status-pressure", label: "Status Pressure", category: TagCategory.UTILITY },
  { slug: "support-buffs", label: "Support and Buffs", category: TagCategory.UTILITY },
  { slug: "stagger", label: "Stagger Control", category: TagCategory.UTILITY },
  { slug: "pve", label: "PvE", category: TagCategory.MODE },
  { slug: "pvp", label: "PvP", category: TagCategory.MODE },
  { slug: "hybrid-mode", label: "Hybrid Mode", category: TagCategory.MODE },
  { slug: "aggressive", label: "Aggressive", category: TagCategory.TEMPO },
  { slug: "explosive", label: "Explosive Tempo", category: TagCategory.TEMPO },
  { slug: "methodical", label: "Methodical", category: TagCategory.TEMPO },
  { slug: "reactive", label: "Reactive", category: TagCategory.TEMPO },
  { slug: "precision", label: "Precision", category: TagCategory.TEMPO },
  { slug: "beginner-friendly", label: "Beginner Friendly", category: TagCategory.ROLE },
  { slug: "glass-cannon", label: "Glass Cannon", category: TagCategory.ROLE },
  { slug: "execution-heavy", label: "Execution Heavy", category: TagCategory.ROLE },
] satisfies TagSeed[];
